name: ValhallaTrinkets
version: '${project.version}'
main: me.athlaeos.valhallatrinkets.ValhallaTrinkets
api-version: 1.16
depend: [ ValhallaMMO ]
authors: [ Athlaeos ]
description: Adds trinkets and a trinket menu hooking into ValhallaMMO, allowing people to wear things like rings or bracers that add to a player's stats
commands:
  trinkets:
    description: Allows the user to open their trinkets menu using a command
    aliases: [ t ]
  trinketeditor:
    description: Allows the user to transform items with various trinket properties
    aliases: [ te ]
permissions:
  trinkets.allowtrinkets:
    default: true
    description: Allows a user to equip and manage their trinkets
  trinkets.setup:
    default: op
    description: Allows the user to load the default ValhallaTrinkets recipes into ValhallaMMO
  trinkets.viewothers:
    default: op
    description: Allows the user to view and modify the trinkets of others
  trinkets.edittrinkets:
    default: op
    description: Allows the user to access the /trinketeditor command, allowing them to edit items to possess trinket properties
  trinkets.keepinventory:
    default: op
    description: Prevents loss of trinkets on death